### ISSUE TITLE
Test can't be passed in special environment

### ISSUE THREAD

**Issue by yaoazhen** [normanzb/Rytm#1]
Actual I can passed in office computer, and failed in home computer. I don't know why~
The Error is : 
ReferenceError: done is not defined.
at Object._onTimeout(......./test/basic.js:550:21)
at Timer.callback(timer.js:83:39)

I think 

The line 541 have a issue. 

541 : it('should pause the execution with specified millisecond', function(){

SHOULD BE 

it('should pause the execution with specified millisecond', function(done){

Right?

**Comment by yaoazhen** [comment]
When I change the memory from 512MB to 1012MB of my virtual machine(Unpass one), the test passed.
When I change the memory back, the test failed.
